// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RpcMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace nms_RpcMessage {
class StringValueDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StringValue> {
} _StringValue_default_instance_;
class IntValueDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<IntValue> {
} _IntValue_default_instance_;
class BinValueDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<BinValue> {
} _BinValue_default_instance_;
class StringPairDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<StringPair> {
} _StringPair_default_instance_;
class RpcMessageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<RpcMessage> {
} _RpcMessage_default_instance_;

namespace protobuf_RpcMessage_2eproto {


void TableStruct::Shutdown() {
  _StringValue_default_instance_.Shutdown();
  _IntValue_default_instance_.Shutdown();
  _BinValue_default_instance_.Shutdown();
  _StringPair_default_instance_.Shutdown();
  _RpcMessage_default_instance_.Shutdown();
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _StringValue_default_instance_.DefaultConstruct();
  _IntValue_default_instance_.DefaultConstruct();
  _BinValue_default_instance_.DefaultConstruct();
  _StringPair_default_instance_.DefaultConstruct();
  _RpcMessage_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER

}  // namespace protobuf_RpcMessage_2eproto

bool Rpc_CmdID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}

bool Rpc_SubCmdID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
      return true;
    default:
      return false;
  }
}

bool ErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}

bool Rpc_KeyCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
      return true;
    default:
      return false;
  }
}

bool Rpc_RunStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
    case 128:
    case 256:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StringValue::kKeyFieldNumber;
const int StringValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StringValue::StringValue()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RpcMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:nms_RpcMessage.StringValue)
}
StringValue::StringValue(const StringValue& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  key_ = from.key_;
  // @@protoc_insertion_point(copy_constructor:nms_RpcMessage.StringValue)
}

void StringValue::SharedCtor() {
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_ = 0;
  _cached_size_ = 0;
}

StringValue::~StringValue() {
  // @@protoc_insertion_point(destructor:nms_RpcMessage.StringValue)
  SharedDtor();
}

void StringValue::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StringValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const StringValue& StringValue::default_instance() {
  protobuf_RpcMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

StringValue* StringValue::New(::google::protobuf::Arena* arena) const {
  StringValue* n = new StringValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StringValue::Clear() {
// @@protoc_insertion_point(message_clear_start:nms_RpcMessage.StringValue)
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_ = 0;
}

bool StringValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nms_RpcMessage.StringValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 key = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &key_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "nms_RpcMessage.StringValue.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nms_RpcMessage.StringValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nms_RpcMessage.StringValue)
  return false;
#undef DO_
}

void StringValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nms_RpcMessage.StringValue)
  // int32 key = 1;
  if (this->key() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->key(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "nms_RpcMessage.StringValue.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:nms_RpcMessage.StringValue)
}

size_t StringValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nms_RpcMessage.StringValue)
  size_t total_size = 0;

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  // int32 key = 1;
  if (this->key() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StringValue::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StringValue*>(&from));
}

void StringValue::MergeFrom(const StringValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nms_RpcMessage.StringValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  if (from.key() != 0) {
    set_key(from.key());
  }
}

void StringValue::CopyFrom(const StringValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nms_RpcMessage.StringValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringValue::IsInitialized() const {
  return true;
}

void StringValue::Swap(StringValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StringValue::InternalSwap(StringValue* other) {
  value_.Swap(&other->value_);
  std::swap(key_, other->key_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string StringValue::GetTypeName() const {
  return "nms_RpcMessage.StringValue";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StringValue

// int32 key = 1;
void StringValue::clear_key() {
  key_ = 0;
}
::google::protobuf::int32 StringValue::key() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.StringValue.key)
  return key_;
}
void StringValue::set_key(::google::protobuf::int32 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.StringValue.key)
}

// string value = 2;
void StringValue::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StringValue::value() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.StringValue.value)
  return value_.GetNoArena();
}
void StringValue::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nms_RpcMessage.StringValue.value)
}
#if LANG_CXX11
void StringValue::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nms_RpcMessage.StringValue.value)
}
#endif
void StringValue::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nms_RpcMessage.StringValue.value)
}
void StringValue::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nms_RpcMessage.StringValue.value)
}
::std::string* StringValue::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.StringValue.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StringValue::release_value() {
  // @@protoc_insertion_point(field_release:nms_RpcMessage.StringValue.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StringValue::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:nms_RpcMessage.StringValue.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IntValue::kKeyFieldNumber;
const int IntValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IntValue::IntValue()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RpcMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:nms_RpcMessage.IntValue)
}
IntValue::IntValue(const IntValue& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&key_, &from.key_,
    reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&key_) + sizeof(value_));
  // @@protoc_insertion_point(copy_constructor:nms_RpcMessage.IntValue)
}

void IntValue::SharedCtor() {
  ::memset(&key_, 0, reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&key_) + sizeof(value_));
  _cached_size_ = 0;
}

IntValue::~IntValue() {
  // @@protoc_insertion_point(destructor:nms_RpcMessage.IntValue)
  SharedDtor();
}

void IntValue::SharedDtor() {
}

void IntValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const IntValue& IntValue::default_instance() {
  protobuf_RpcMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

IntValue* IntValue::New(::google::protobuf::Arena* arena) const {
  IntValue* n = new IntValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void IntValue::Clear() {
// @@protoc_insertion_point(message_clear_start:nms_RpcMessage.IntValue)
  ::memset(&key_, 0, reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&key_) + sizeof(value_));
}

bool IntValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nms_RpcMessage.IntValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 key = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &key_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 value = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nms_RpcMessage.IntValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nms_RpcMessage.IntValue)
  return false;
#undef DO_
}

void IntValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nms_RpcMessage.IntValue)
  // int32 key = 1;
  if (this->key() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->key(), output);
  }

  // int32 value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:nms_RpcMessage.IntValue)
}

size_t IntValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nms_RpcMessage.IntValue)
  size_t total_size = 0;

  // int32 key = 1;
  if (this->key() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->key());
  }

  // int32 value = 2;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void IntValue::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const IntValue*>(&from));
}

void IntValue::MergeFrom(const IntValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nms_RpcMessage.IntValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.key() != 0) {
    set_key(from.key());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void IntValue::CopyFrom(const IntValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nms_RpcMessage.IntValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IntValue::IsInitialized() const {
  return true;
}

void IntValue::Swap(IntValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IntValue::InternalSwap(IntValue* other) {
  std::swap(key_, other->key_);
  std::swap(value_, other->value_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string IntValue::GetTypeName() const {
  return "nms_RpcMessage.IntValue";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// IntValue

// int32 key = 1;
void IntValue::clear_key() {
  key_ = 0;
}
::google::protobuf::int32 IntValue::key() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.IntValue.key)
  return key_;
}
void IntValue::set_key(::google::protobuf::int32 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.IntValue.key)
}

// int32 value = 2;
void IntValue::clear_value() {
  value_ = 0;
}
::google::protobuf::int32 IntValue::value() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.IntValue.value)
  return value_;
}
void IntValue::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.IntValue.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BinValue::kKeyFieldNumber;
const int BinValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BinValue::BinValue()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RpcMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:nms_RpcMessage.BinValue)
}
BinValue::BinValue(const BinValue& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  key_ = from.key_;
  // @@protoc_insertion_point(copy_constructor:nms_RpcMessage.BinValue)
}

void BinValue::SharedCtor() {
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_ = 0;
  _cached_size_ = 0;
}

BinValue::~BinValue() {
  // @@protoc_insertion_point(destructor:nms_RpcMessage.BinValue)
  SharedDtor();
}

void BinValue::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BinValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BinValue& BinValue::default_instance() {
  protobuf_RpcMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

BinValue* BinValue::New(::google::protobuf::Arena* arena) const {
  BinValue* n = new BinValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BinValue::Clear() {
// @@protoc_insertion_point(message_clear_start:nms_RpcMessage.BinValue)
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_ = 0;
}

bool BinValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nms_RpcMessage.BinValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 key = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &key_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes value = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nms_RpcMessage.BinValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nms_RpcMessage.BinValue)
  return false;
#undef DO_
}

void BinValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nms_RpcMessage.BinValue)
  // int32 key = 1;
  if (this->key() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->key(), output);
  }

  // bytes value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:nms_RpcMessage.BinValue)
}

size_t BinValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nms_RpcMessage.BinValue)
  size_t total_size = 0;

  // bytes value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->value());
  }

  // int32 key = 1;
  if (this->key() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BinValue::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BinValue*>(&from));
}

void BinValue::MergeFrom(const BinValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nms_RpcMessage.BinValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  if (from.key() != 0) {
    set_key(from.key());
  }
}

void BinValue::CopyFrom(const BinValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nms_RpcMessage.BinValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BinValue::IsInitialized() const {
  return true;
}

void BinValue::Swap(BinValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BinValue::InternalSwap(BinValue* other) {
  value_.Swap(&other->value_);
  std::swap(key_, other->key_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string BinValue::GetTypeName() const {
  return "nms_RpcMessage.BinValue";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BinValue

// int32 key = 1;
void BinValue::clear_key() {
  key_ = 0;
}
::google::protobuf::int32 BinValue::key() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.BinValue.key)
  return key_;
}
void BinValue::set_key(::google::protobuf::int32 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.BinValue.key)
}

// bytes value = 2;
void BinValue::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& BinValue::value() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.BinValue.value)
  return value_.GetNoArena();
}
void BinValue::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nms_RpcMessage.BinValue.value)
}
#if LANG_CXX11
void BinValue::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nms_RpcMessage.BinValue.value)
}
#endif
void BinValue::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nms_RpcMessage.BinValue.value)
}
void BinValue::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nms_RpcMessage.BinValue.value)
}
::std::string* BinValue::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.BinValue.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* BinValue::release_value() {
  // @@protoc_insertion_point(field_release:nms_RpcMessage.BinValue.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void BinValue::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:nms_RpcMessage.BinValue.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StringPair::kKeyFieldNumber;
const int StringPair::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StringPair::StringPair()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RpcMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:nms_RpcMessage.StringPair)
}
StringPair::StringPair(const StringPair& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:nms_RpcMessage.StringPair)
}

void StringPair::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

StringPair::~StringPair() {
  // @@protoc_insertion_point(destructor:nms_RpcMessage.StringPair)
  SharedDtor();
}

void StringPair::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StringPair::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const StringPair& StringPair::default_instance() {
  protobuf_RpcMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

StringPair* StringPair::New(::google::protobuf::Arena* arena) const {
  StringPair* n = new StringPair;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StringPair::Clear() {
// @@protoc_insertion_point(message_clear_start:nms_RpcMessage.StringPair)
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool StringPair::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nms_RpcMessage.StringPair)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "nms_RpcMessage.StringPair.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "nms_RpcMessage.StringPair.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nms_RpcMessage.StringPair)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nms_RpcMessage.StringPair)
  return false;
#undef DO_
}

void StringPair::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nms_RpcMessage.StringPair)
  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "nms_RpcMessage.StringPair.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "nms_RpcMessage.StringPair.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:nms_RpcMessage.StringPair)
}

size_t StringPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nms_RpcMessage.StringPair)
  size_t total_size = 0;

  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StringPair::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StringPair*>(&from));
}

void StringPair::MergeFrom(const StringPair& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nms_RpcMessage.StringPair)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void StringPair::CopyFrom(const StringPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nms_RpcMessage.StringPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringPair::IsInitialized() const {
  return true;
}

void StringPair::Swap(StringPair* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StringPair::InternalSwap(StringPair* other) {
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string StringPair::GetTypeName() const {
  return "nms_RpcMessage.StringPair";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StringPair

// string key = 1;
void StringPair::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StringPair::key() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.StringPair.key)
  return key_.GetNoArena();
}
void StringPair::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nms_RpcMessage.StringPair.key)
}
#if LANG_CXX11
void StringPair::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nms_RpcMessage.StringPair.key)
}
#endif
void StringPair::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nms_RpcMessage.StringPair.key)
}
void StringPair::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nms_RpcMessage.StringPair.key)
}
::std::string* StringPair::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.StringPair.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StringPair::release_key() {
  // @@protoc_insertion_point(field_release:nms_RpcMessage.StringPair.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StringPair::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:nms_RpcMessage.StringPair.key)
}

// string value = 2;
void StringPair::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& StringPair::value() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.StringPair.value)
  return value_.GetNoArena();
}
void StringPair::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nms_RpcMessage.StringPair.value)
}
#if LANG_CXX11
void StringPair::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nms_RpcMessage.StringPair.value)
}
#endif
void StringPair::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nms_RpcMessage.StringPair.value)
}
void StringPair::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nms_RpcMessage.StringPair.value)
}
::std::string* StringPair::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.StringPair.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* StringPair::release_value() {
  // @@protoc_insertion_point(field_release:nms_RpcMessage.StringPair.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void StringPair::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:nms_RpcMessage.StringPair.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcMessage::kMsgnoFieldNumber;
const int RpcMessage::kCmdFieldNumber;
const int RpcMessage::kSubcmdFieldNumber;
const int RpcMessage::kErrorFieldNumber;
const int RpcMessage::kInfoFieldNumber;
const int RpcMessage::kStrvalsFieldNumber;
const int RpcMessage::kIntvalsFieldNumber;
const int RpcMessage::kBinvalsFieldNumber;
const int RpcMessage::kStrpairsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcMessage::RpcMessage()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RpcMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:nms_RpcMessage.RpcMessage)
}
RpcMessage::RpcMessage(const RpcMessage& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      strvals_(from.strvals_),
      intvals_(from.intvals_),
      binvals_(from.binvals_),
      strpairs_(from.strpairs_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&msgno_, &from.msgno_,
    reinterpret_cast<char*>(&info_) -
    reinterpret_cast<char*>(&msgno_) + sizeof(info_));
  // @@protoc_insertion_point(copy_constructor:nms_RpcMessage.RpcMessage)
}

void RpcMessage::SharedCtor() {
  ::memset(&msgno_, 0, reinterpret_cast<char*>(&info_) -
    reinterpret_cast<char*>(&msgno_) + sizeof(info_));
  _cached_size_ = 0;
}

RpcMessage::~RpcMessage() {
  // @@protoc_insertion_point(destructor:nms_RpcMessage.RpcMessage)
  SharedDtor();
}

void RpcMessage::SharedDtor() {
}

void RpcMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RpcMessage& RpcMessage::default_instance() {
  protobuf_RpcMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

RpcMessage* RpcMessage::New(::google::protobuf::Arena* arena) const {
  RpcMessage* n = new RpcMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:nms_RpcMessage.RpcMessage)
  strvals_.Clear();
  intvals_.Clear();
  binvals_.Clear();
  strpairs_.Clear();
  ::memset(&msgno_, 0, reinterpret_cast<char*>(&info_) -
    reinterpret_cast<char*>(&msgno_) + sizeof(info_));
}

bool RpcMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nms_RpcMessage.RpcMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // fixed32 msgno = 1;
      case 1: {
        if (tag == 13u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &msgno_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 cmd = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cmd_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 subcmd = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &subcmd_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 error = 6;
      case 6: {
        if (tag == 48u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 info = 7;
      case 7: {
        if (tag == 56u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &info_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .nms_RpcMessage.StringValue strvals = 10;
      case 10: {
        if (tag == 82u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_strvals()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .nms_RpcMessage.IntValue intvals = 11;
      case 11: {
        if (tag == 90u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_intvals()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .nms_RpcMessage.BinValue binvals = 12;
      case 12: {
        if (tag == 98u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_binvals()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .nms_RpcMessage.StringPair strpairs = 13;
      case 13: {
        if (tag == 106u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_strpairs()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nms_RpcMessage.RpcMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nms_RpcMessage.RpcMessage)
  return false;
#undef DO_
}

void RpcMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nms_RpcMessage.RpcMessage)
  // fixed32 msgno = 1;
  if (this->msgno() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->msgno(), output);
  }

  // int32 cmd = 2;
  if (this->cmd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->cmd(), output);
  }

  // int32 subcmd = 3;
  if (this->subcmd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->subcmd(), output);
  }

  // int32 error = 6;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->error(), output);
  }

  // int32 info = 7;
  if (this->info() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->info(), output);
  }

  // repeated .nms_RpcMessage.StringValue strvals = 10;
  for (unsigned int i = 0, n = this->strvals_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      10, this->strvals(i), output);
  }

  // repeated .nms_RpcMessage.IntValue intvals = 11;
  for (unsigned int i = 0, n = this->intvals_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      11, this->intvals(i), output);
  }

  // repeated .nms_RpcMessage.BinValue binvals = 12;
  for (unsigned int i = 0, n = this->binvals_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      12, this->binvals(i), output);
  }

  // repeated .nms_RpcMessage.StringPair strpairs = 13;
  for (unsigned int i = 0, n = this->strpairs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      13, this->strpairs(i), output);
  }

  // @@protoc_insertion_point(serialize_end:nms_RpcMessage.RpcMessage)
}

size_t RpcMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:nms_RpcMessage.RpcMessage)
  size_t total_size = 0;

  // repeated .nms_RpcMessage.StringValue strvals = 10;
  {
    unsigned int count = this->strvals_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->strvals(i));
    }
  }

  // repeated .nms_RpcMessage.IntValue intvals = 11;
  {
    unsigned int count = this->intvals_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->intvals(i));
    }
  }

  // repeated .nms_RpcMessage.BinValue binvals = 12;
  {
    unsigned int count = this->binvals_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->binvals(i));
    }
  }

  // repeated .nms_RpcMessage.StringPair strpairs = 13;
  {
    unsigned int count = this->strpairs_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->strpairs(i));
    }
  }

  // fixed32 msgno = 1;
  if (this->msgno() != 0) {
    total_size += 1 + 4;
  }

  // int32 cmd = 2;
  if (this->cmd() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cmd());
  }

  // int32 subcmd = 3;
  if (this->subcmd() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->subcmd());
  }

  // int32 error = 6;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  // int32 info = 7;
  if (this->info() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->info());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RpcMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RpcMessage*>(&from));
}

void RpcMessage::MergeFrom(const RpcMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:nms_RpcMessage.RpcMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  strvals_.MergeFrom(from.strvals_);
  intvals_.MergeFrom(from.intvals_);
  binvals_.MergeFrom(from.binvals_);
  strpairs_.MergeFrom(from.strpairs_);
  if (from.msgno() != 0) {
    set_msgno(from.msgno());
  }
  if (from.cmd() != 0) {
    set_cmd(from.cmd());
  }
  if (from.subcmd() != 0) {
    set_subcmd(from.subcmd());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
  if (from.info() != 0) {
    set_info(from.info());
  }
}

void RpcMessage::CopyFrom(const RpcMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nms_RpcMessage.RpcMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcMessage::IsInitialized() const {
  return true;
}

void RpcMessage::Swap(RpcMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcMessage::InternalSwap(RpcMessage* other) {
  strvals_.UnsafeArenaSwap(&other->strvals_);
  intvals_.UnsafeArenaSwap(&other->intvals_);
  binvals_.UnsafeArenaSwap(&other->binvals_);
  strpairs_.UnsafeArenaSwap(&other->strpairs_);
  std::swap(msgno_, other->msgno_);
  std::swap(cmd_, other->cmd_);
  std::swap(subcmd_, other->subcmd_);
  std::swap(error_, other->error_);
  std::swap(info_, other->info_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string RpcMessage::GetTypeName() const {
  return "nms_RpcMessage.RpcMessage";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RpcMessage

// fixed32 msgno = 1;
void RpcMessage::clear_msgno() {
  msgno_ = 0u;
}
::google::protobuf::uint32 RpcMessage::msgno() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.msgno)
  return msgno_;
}
void RpcMessage::set_msgno(::google::protobuf::uint32 value) {
  
  msgno_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.RpcMessage.msgno)
}

// int32 cmd = 2;
void RpcMessage::clear_cmd() {
  cmd_ = 0;
}
::google::protobuf::int32 RpcMessage::cmd() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.cmd)
  return cmd_;
}
void RpcMessage::set_cmd(::google::protobuf::int32 value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.RpcMessage.cmd)
}

// int32 subcmd = 3;
void RpcMessage::clear_subcmd() {
  subcmd_ = 0;
}
::google::protobuf::int32 RpcMessage::subcmd() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.subcmd)
  return subcmd_;
}
void RpcMessage::set_subcmd(::google::protobuf::int32 value) {
  
  subcmd_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.RpcMessage.subcmd)
}

// int32 error = 6;
void RpcMessage::clear_error() {
  error_ = 0;
}
::google::protobuf::int32 RpcMessage::error() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.error)
  return error_;
}
void RpcMessage::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.RpcMessage.error)
}

// int32 info = 7;
void RpcMessage::clear_info() {
  info_ = 0;
}
::google::protobuf::int32 RpcMessage::info() const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.info)
  return info_;
}
void RpcMessage::set_info(::google::protobuf::int32 value) {
  
  info_ = value;
  // @@protoc_insertion_point(field_set:nms_RpcMessage.RpcMessage.info)
}

// repeated .nms_RpcMessage.StringValue strvals = 10;
int RpcMessage::strvals_size() const {
  return strvals_.size();
}
void RpcMessage::clear_strvals() {
  strvals_.Clear();
}
const ::nms_RpcMessage::StringValue& RpcMessage::strvals(int index) const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.strvals)
  return strvals_.Get(index);
}
::nms_RpcMessage::StringValue* RpcMessage::mutable_strvals(int index) {
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.RpcMessage.strvals)
  return strvals_.Mutable(index);
}
::nms_RpcMessage::StringValue* RpcMessage::add_strvals() {
  // @@protoc_insertion_point(field_add:nms_RpcMessage.RpcMessage.strvals)
  return strvals_.Add();
}
::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::StringValue >*
RpcMessage::mutable_strvals() {
  // @@protoc_insertion_point(field_mutable_list:nms_RpcMessage.RpcMessage.strvals)
  return &strvals_;
}
const ::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::StringValue >&
RpcMessage::strvals() const {
  // @@protoc_insertion_point(field_list:nms_RpcMessage.RpcMessage.strvals)
  return strvals_;
}

// repeated .nms_RpcMessage.IntValue intvals = 11;
int RpcMessage::intvals_size() const {
  return intvals_.size();
}
void RpcMessage::clear_intvals() {
  intvals_.Clear();
}
const ::nms_RpcMessage::IntValue& RpcMessage::intvals(int index) const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.intvals)
  return intvals_.Get(index);
}
::nms_RpcMessage::IntValue* RpcMessage::mutable_intvals(int index) {
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.RpcMessage.intvals)
  return intvals_.Mutable(index);
}
::nms_RpcMessage::IntValue* RpcMessage::add_intvals() {
  // @@protoc_insertion_point(field_add:nms_RpcMessage.RpcMessage.intvals)
  return intvals_.Add();
}
::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::IntValue >*
RpcMessage::mutable_intvals() {
  // @@protoc_insertion_point(field_mutable_list:nms_RpcMessage.RpcMessage.intvals)
  return &intvals_;
}
const ::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::IntValue >&
RpcMessage::intvals() const {
  // @@protoc_insertion_point(field_list:nms_RpcMessage.RpcMessage.intvals)
  return intvals_;
}

// repeated .nms_RpcMessage.BinValue binvals = 12;
int RpcMessage::binvals_size() const {
  return binvals_.size();
}
void RpcMessage::clear_binvals() {
  binvals_.Clear();
}
const ::nms_RpcMessage::BinValue& RpcMessage::binvals(int index) const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.binvals)
  return binvals_.Get(index);
}
::nms_RpcMessage::BinValue* RpcMessage::mutable_binvals(int index) {
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.RpcMessage.binvals)
  return binvals_.Mutable(index);
}
::nms_RpcMessage::BinValue* RpcMessage::add_binvals() {
  // @@protoc_insertion_point(field_add:nms_RpcMessage.RpcMessage.binvals)
  return binvals_.Add();
}
::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::BinValue >*
RpcMessage::mutable_binvals() {
  // @@protoc_insertion_point(field_mutable_list:nms_RpcMessage.RpcMessage.binvals)
  return &binvals_;
}
const ::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::BinValue >&
RpcMessage::binvals() const {
  // @@protoc_insertion_point(field_list:nms_RpcMessage.RpcMessage.binvals)
  return binvals_;
}

// repeated .nms_RpcMessage.StringPair strpairs = 13;
int RpcMessage::strpairs_size() const {
  return strpairs_.size();
}
void RpcMessage::clear_strpairs() {
  strpairs_.Clear();
}
const ::nms_RpcMessage::StringPair& RpcMessage::strpairs(int index) const {
  // @@protoc_insertion_point(field_get:nms_RpcMessage.RpcMessage.strpairs)
  return strpairs_.Get(index);
}
::nms_RpcMessage::StringPair* RpcMessage::mutable_strpairs(int index) {
  // @@protoc_insertion_point(field_mutable:nms_RpcMessage.RpcMessage.strpairs)
  return strpairs_.Mutable(index);
}
::nms_RpcMessage::StringPair* RpcMessage::add_strpairs() {
  // @@protoc_insertion_point(field_add:nms_RpcMessage.RpcMessage.strpairs)
  return strpairs_.Add();
}
::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::StringPair >*
RpcMessage::mutable_strpairs() {
  // @@protoc_insertion_point(field_mutable_list:nms_RpcMessage.RpcMessage.strpairs)
  return &strpairs_;
}
const ::google::protobuf::RepeatedPtrField< ::nms_RpcMessage::StringPair >&
RpcMessage::strpairs() const {
  // @@protoc_insertion_point(field_list:nms_RpcMessage.RpcMessage.strpairs)
  return strpairs_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace nms_RpcMessage

// @@protoc_insertion_point(global_scope)
