
#ifndef MODULE_DEFINES_HHH
#define MODULE_DEFINES_HHH

enum
{
    CATEGORY_BASE_VALUE = 0x1,
    CATEGORY_COUNT = 32,
};

typedef enum
{
    CATEGORY_SCHEDULER =        0,
    CATEGORY_LOGGER =           CATEGORY_BASE_VALUE,
    CATEGORY_CENTER_AGENT =     CATEGORY_BASE_VALUE << 1,
    CATEGORY_UI_AGENT =         CATEGORY_BASE_VALUE << 2,
    CATEGORY_FILE_MONITOR =     CATEGORY_BASE_VALUE << 3,
    CATEGORY_PORCESS_MONITOR =  CATEGORY_BASE_VALUE << 4,
    CATEGORY_FILE_SCANER =      CATEGORY_BASE_VALUE << 5,
    CATEGORY_FILE_REPORTER =    CATEGORY_BASE_VALUE << 6,
    CATEGORY_RPC_SERVER =       CATEGORY_BASE_VALUE << 7,
    CATEGORY_SYSINFO =          CATEGORY_BASE_VALUE << 8,
    CATEGORY_FILE_DIGEST =      CATEGORY_BASE_VALUE << 9,
    CATEGORY_USB_MONITOR =      CATEGORY_BASE_VALUE << 10,
    CATEGORY_VC_CLIENT =        CATEGORY_BASE_VALUE << 11,
    CATEGORY_VC_SERVER =        CATEGORY_BASE_VALUE << 12,
    CATEGORY_SCNNER =           CATEGORY_BASE_VALUE << 13,
    CATEGORY_RPCSRV =           CATEGORY_BASE_VALUE << 14,
    CATEGORY_AVX =              CATEGORY_BASE_VALUE << 15,
    CATEGORY_NET_MONITOR =      CATEGORY_BASE_VALUE << 16,
    CATEGORY_UPGRADE =          CATEGORY_BASE_VALUE << 17,

    CATEGORY_OTHERS =           CATEGORY_BASE_VALUE << 31,
}module_category_t;

#endif

